services:
    # Upload handler
    upload.handler:
        class:        MeloLab\BioGestion\FileUploadBundle\Service\UploadHandler
        autowire: true
#        arguments:    [ "@doctrine.orm.entity_manager", "@service_container", "@security.authorization_checker", "@translator", "@form.factory", "@router", "@vich_uploader.property_mapping_factory" ]

    twig.helper_extension:
        class: MeloLab\BioGestion\FileUploadBundle\Twig\HelperExtension
        arguments:    [ "@service_container" ]
        tags:
            - { name: twig.extension }
