services:
    # Upload handler
    upload.handler:
        class:        MeloLab\BioGestion\FileUploadBundle\Service\UploadHandler
        arguments:    [ @doctrine.orm.entity_manager, @service_container, @security.context, @translator, @form.factory, @router ]            

    twig.helper_extension:
        class: MeloLab\BioGestion\FileUploadBundle\Twig\HelperExtension
        arguments:    [ "@service_container" ]
        tags:
            - { name: twig.extension }
